2024-11-10 20:31:31,362 | INFO | "test_challenge" выполнен успешно
2024-11-10 20:31:31,363 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-11-10 20:31:31,367 | WARNING | Traceback (most recent call last):
  File "C:\Users\egorp\PycharmProjects\pythonProject1\tests_12_4.py", line 82, in test_run
    runner = Runner(2)
  File "C:\Users\egorp\PycharmProjects\pythonProject1\tests_12_4.py", line 14, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-11-10 20:31:31,368 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-11-10 20:31:31,369 | WARNING | Traceback (most recent call last):
  File "C:\Users\egorp\PycharmProjects\pythonProject1\tests_12_4.py", line 71, in test_walk
    runner = Runner("Вася", -5)
             ~~~~~~^^^^^^^^^^^^
  File "C:\Users\egorp\PycharmProjects\pythonProject1\tests_12_4.py", line 19, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

